version: '3.9'

services:
  savio_api:
    build:
      context: ./Savio/Savio.API
    ports:
      - "5000:80"
    networks:
      - backend

  user_api:
    build:
      context: ./Savio/User.API
    ports:
      - "5001:80"
    networks:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - savio_api
      - user_api
    networks:
      - backend

networks:
  backend:
    driver: bridge
