services:
  - type: web
    name: savio-api
    runtime: docker
    repo: https://github.com/star1020/SavioAPI.git
    region: singapore
    plan: free
    dockerfilePath: Savio/Savio.API/Dockerfile
    buildCommand: ""
    startCommand: ""
